# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# this code is run by using python 3.8 environment instead of anaconda

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(374, 312)
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        
        # create input username
        self.inputUsername = QtWidgets.QLineEdit(self.centralwidget)
        self.inputUsername.setGeometry(QtCore.QRect(152, 100, 111, 22))
        self.inputUsername.setObjectName("inputUsername")
        
        # create input password
        self.inputPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.inputPassword.setGeometry(QtCore.QRect(152, 140, 111, 22))
        self.inputPassword.setObjectName("inputPassword")

        # hide the password
        self.inputPassword.setEchoMode(QtWidgets.QLineEdit.Password)
        
        # create login button
        self.loginButton = QtWidgets.QPushButton(self.centralwidget)
        self.loginButton.setGeometry(QtCore.QRect(150, 190, 93, 28))
        self.loginButton.setObjectName("loginButton")
        self.loginButton.clicked.connect(self.check_password)
        
        
        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(70, 100, 71, 16))
        self.usernameLabel.setObjectName("usernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)
        self.passwordLabel.setGeometry(QtCore.QRect(70, 140, 71, 16))
        self.passwordLabel.setObjectName("passwordLabel")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login Page"))
        self.loginButton.setText(_translate("Login", "Login"))
        self.usernameLabel.setText(_translate("Login", "Username"))
        self.passwordLabel.setText(_translate("Login", "Password"))
        
    def check_password(self):
        msg = QtWidgets.QMessageBox()
        
        if self.inputUsername.text() == 'admin' and self.inputPassword.text() == 'password':
            msg.setText('Success')
            msg.resize
            msg.exec_()
            app.quit()
            print("success")
        
        else:
            msg.setText('Incorrect Password')
            msg.exec_()
            print("fail")
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())

